services:
  selenoid:
    image: aerokube/selenoid:1.11.3
    container_name: selenoid
    ports:
      - "4444:4444"
    volumes:
      - ./selenoid:/etc/selenoid:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Europe/Moscow
      - DOCKER_API_VERSION=1.40
    command:
      - "-conf"
      - "/etc/selenoid/browsers.json"
      - "-limit"
      - "5"
      - "-container-network"
      - "selenium-net"
    networks:
      - selenium-net
    restart: unless-stopped

  tests:
    build: .
    environment:
      - SELENIUM_HOST=http://selenoid:4444/wd/hub
      - CI=true
    volumes:
      - ./allure_results/selenoid:/app/allure_results/selenoid
      - ./allure-report:/app/allure-report
      - pip-cache:/root/.cache/pip
    depends_on:
      - selenoid
    networks:
      - selenium-net

networks:
  selenium-net:
    driver: bridge
    name: selenium-net

volumes:
  pip-cache:
